/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: lucasbaze (https://sketchfab.com/lucasbaze)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/low-poly-decorated-christmas-tree-with-presents-89bab7f26bc7418d96beb3ac0059f607
title: Low Poly Decorated Christmas Tree with Presents
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/tree.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.mesh_0.geometry}
          material={materials.Standard907763}
        />
        <mesh
          geometry={nodes.mesh_1.geometry}
          material={nodes.mesh_1.material}
        />
        <mesh
          geometry={nodes.mesh_2.geometry}
          material={nodes.mesh_2.material}
        />
        <mesh
          geometry={nodes.mesh_3.geometry}
          material={materials.Standard477342}
        />
        <mesh
          geometry={nodes.mesh_4.geometry}
          material={nodes.mesh_4.material}
        />
        <mesh
          geometry={nodes.mesh_5.geometry}
          material={nodes.mesh_5.material}
        />
        <mesh
          geometry={nodes.mesh_6.geometry}
          material={nodes.mesh_6.material}
        />
        <mesh
          geometry={nodes.mesh_7.geometry}
          material={nodes.mesh_7.material}
        />
        <mesh
          geometry={nodes.mesh_8.geometry}
          material={nodes.mesh_8.material}
        />
        <mesh
          geometry={nodes.mesh_9.geometry}
          material={nodes.mesh_9.material}
        />
        <mesh
          geometry={nodes.mesh_10.geometry}
          material={nodes.mesh_10.material}
        />
        <mesh
          geometry={nodes.mesh_11.geometry}
          material={nodes.mesh_11.material}
        />
        <mesh
          geometry={nodes.mesh_12.geometry}
          material={nodes.mesh_12.material}
        />
        <mesh
          geometry={nodes.mesh_13.geometry}
          material={materials.StandardF0EF00}
        />
        <mesh
          geometry={nodes.mesh_14.geometry}
          material={nodes.mesh_14.material}
        />
        <mesh
          geometry={nodes.mesh_15.geometry}
          material={nodes.mesh_15.material}
        />
        <mesh
          geometry={nodes.mesh_16.geometry}
          material={materials.StandardFFAE1F}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/tree.gltf')
